name: langchain-extract-entities

services:
  postgres:
    image: postgres:16
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U langchain -d langchain -W langchain"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./llm/ner-llm
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .local.env
    environment:
      - PG_HOST=postgres

        # Define CORS origins for dev work on UI
      - CORS_ORIGINS=http://localhost:3000
    ports:
      - "8000:8000" # Backend is accessible on localhost:8100
    depends_on:
      - postgres
    volumes:
      - ./llm/ner-llm:/ner-llm

volumes:
  postgres_data:
