name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10
        options: --privileged
        ports:
          - 5432:5432 # PostgreSQL default port
        env:
          DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker images
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: |
          docker-compose exec -T ner-llm npm test

      - name: Stop and remove containers
        if: always()
        run: docker-compose down
